### ISSUE TITLE
Dithering

### ISSUE THREAD

**Issue by BoomBoxHPB** [dbanno/ConnectIQ-8-BitWatch#1]
I noticed that VivoActive appears to dither the empty (gray) hearts. There's a dithering option when naming the resources in the XML, and the default is to enable dithering.

**Comment by dbanno** [comment]
Thank you for the tip! I've just uploaded a new version to Garmin Connect. The hearts look much nicer now!

**Comment by BoomBoxHPB** [comment]
Not a problem! FYI, the watchface has gotten a good following (probably ~30% of the vivoactives I see).
